### ISSUE TITLE
Error: Invalid name given. Name must be unique

### ISSUE THREAD

**Issue by hwhsu1231** [crowdin/translate-readme#41]
### Problem Description

Recently, I tested this GitHub Action, but it failed with the following error:

```
Error: Invalid name given. Name must be unique
```

The following is my test action:

<details><summary>Click to expand action</summary>

```yml
      - name: Translate Readme
        uses: crowdin/translate-readme@v0.1.0
        with:
          upload_sources: true
          download_translations: false
          language_switcher: true
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
```

</details>

The following is my test README.md:

<details><summary>Click to expand README.md</summary>

```md
<!-- TRANSLATE-README-LANGUAGES-START -->
<h2 id="table-of-contents">
Table of Contents
</h2>

* <a href="#introduction">Introduction</a>
* <a href="#documentation">Documentation</a>
* <a href="#progress-of-translations">Progress of Translations</a>
* <a href="#preview-translations">Preview Translations</a>
  * <a href="#preview-in-local-build">Preview in Local Build</a>
  * <a href="#preview-in-gh-pages">Preview in GitHub Pages</a>
* <a href="#contributors-list">Contributors</a>
  * <a href="#github-contributors">GitHub Contributors</a>
  * <a href="#crowdin-contributors">Crowdin Contributors</a>
<!-- TRANSLATE-README-LANGUAGES-END -->
```

</details>

And the following is my full log of this step:

<details><summary>Click to expand logs</summary>

```
Run crowdin/translate-readme@v0.1.0
  with:
    upload_sources: true
    download_translations: false
    language_switcher: true
    file: README.md
    destination: ./
  env:
    CROWDIN_PROJECT_ID: ***
    CROWDIN_PERSONAL_TOKEN: ***
Start...
Adding language switcher to README.md...
Uploading sources...
Error: Invalid name given. Name must be unique
```

</details>

### Versions

crowdin/translate-readme@v0.1.0
